/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import clases.GrafoSistemaPlanetario;
import clases.Planeta;
import clases.SistemaPlanetario;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.ImageIcon;

import utils.CargadorImagen;

/**
 *
 * @author Carolina
 */
public class NebulosaPanel extends javax.swing.JPanel {

    /**
     * Creates new form panSisplanetario
     */
    int x;
    int y;
    int i=0;
    
    public static GrafoSistemaPlanetario grafoSistemaPlanetario;
    
    private static List<Planeta> listaPlaneta;

    //va poner la lista que reciba a la lista de planetas general
    public static void agregarPlaneta(List<Planeta> listaPlaneta   ){
       NebulosaPanel.listaPlaneta = listaPlaneta;
        System.out.println("plantas agregados " + listaPlaneta.size());
    }
    public NebulosaPanel() {
        initComponents();
        grafoSistemaPlanetario= new GrafoSistemaPlanetario();
       // listaPlaneta.is
        
    }
    //fondo ventana sistema planetario
    @Override
    public void paint(Graphics g){
        g.drawImage(CargadorImagen.obtenerImagen("src\\Imagenes\\fondosistema.png"), 0, 0, 1024, 700,null);//
       
        
    }
    public void pintarSistemaPlanetario(SistemaPlanetario sistemaPlanetario){
       Graphics g = getGraphics();
       //Execption para poder leer una imagen
        BufferedImage imgSistema = CargadorImagen.obtenerImagen("src\\Imagenes\\sistemaplanetario.png");
        
        g.drawImage(imgSistema, sistemaPlanetario.getX(), sistemaPlanetario.getY(), 50, 50, this);  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //pinta el sistemas planetarios
        if(!evt.isMetaDown()){
            x=evt.getX();
            y=evt.getY();
            SistemaPlanetario sistemaPlanetario = new SistemaPlanetario(x,y,i);
            pintarSistemaPlanetario(sistemaPlanetario);
          grafoSistemaPlanetario.adicionarSistemaPlanetario(sistemaPlanetario);
            i++;
       
       grafoSistemaPlanetario.imprimirGrafo();
       UniversoPanel.agregarSistemaPlanetario(grafoSistemaPlanetario.getListaSistemasPlanetarios());
       System.out.println("la lista de sistemas es" + grafoSistemaPlanetario.getTotalSitemasPlanetarios());
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

}
