/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import clases.GrafoNebulosa;
import clases.Nebulosa;
import clases.SistemaPlanetario;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.LinkedList;
import java.util.List;
//import static paneles.NebulosaPanel.grafoSistemaPlanetario;
import utils.CargadorImagen;

/**
 *
 * @author Carolina
 */
public class UniversoPanel extends javax.swing.JPanel {

//    private static void agregarNebulosa(List<Nebulosa> listaNebulosas) {
//        UniversoPanel.listaNebulosas = listaNebulosas;
//    }

    /**
     * Creates new form panNebulosa
     */
    public int x;
    public int y;
    public int i=0;
    public static GrafoNebulosa grafoNebulosa;
    public static List<SistemaPlanetario> listaSistemaPlanetarios;
    public static List<Nebulosa> listaNebulosas;
    //public LinkedList<LinkedList<Nebulosa>> ListaNebulosa;
    public UniversoPanel() {
        initComponents();
        this.setSize(1024, 700);
        grafoNebulosa = new GrafoNebulosa();
    }
    
    //va poner la lista que reciba a la lista de sistemas planetarios general
    public static void agregarSistemaPlanetario(List<SistemaPlanetario> listaSistemaPlanetarios  ){
       UniversoPanel.listaSistemaPlanetarios = listaSistemaPlanetarios;
    }
   
    //fondo ventana nebulosa
    @Override
    public void paint(Graphics g){
        g.drawImage(CargadorImagen.obtenerImagen("src\\Imagenes\\nebulosa.jpg"), 0, 0, 1024, 700,null);//
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
        
    }
    
    
    
    
    public void pintarNebulosa(Nebulosa nebulosa){
       Graphics g = getGraphics();
       //Execption para poder leer una imagen
        BufferedImage imgNebulosa = CargadorImagen.obtenerImagen("src\\Imagenes\\nebulosa.png");
        
        g.drawImage(imgNebulosa, nebulosa.getX(), nebulosa.getY(), 50, 50, this);  
         grafoNebulosa.adicionarNebulosa(nebulosa);
            i++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //pinta el sistemas planetarios
        if(!evt.isMetaDown()){
            x=evt.getX();
            y=evt.getY();
            Nebulosa nebulosa = new Nebulosa(x,y,i);
            pintarNebulosa(nebulosa);
//          grafoNebulosa.adicionarNebulosa(nebulosa);
//            i++;
       
       grafoNebulosa.imprimirGrafo();
      // UniversoPanel.agregarNebulosa(grafoNebulosa.getListaNebulosas());
       System.out.println("la lista de nebulosa es" + grafoNebulosa.getTotalNebulosas());
    }                          
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
